/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dto.FoodInfoDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.YogioInter;
import model.YogioModel;

/**
 *
 * @author xxseokkixx
 */
public class FoodDetailView extends javax.swing.JPanel {

    // 음식번호에 따른 이미지 호출을 위한 멤버필드 변수.
    private int priNum;
    // main 
    private YogioGUI main;
    // jFrame클래스 이용을 위한 상위객체 선언
    private JFrame jf;

    /**
     * Creates new form FoodDetailView
     */
    public FoodDetailView(YogioGUI main) {
        this.main = main;
        initComponents();
        jf = new JFrame();
        jf.add(this);
        // add한 객체 크기만큼 JFrame의 크기를 결정
        jf.pack();
        // 주문버튼이동.
        detailOrderBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String custid = "";
                main.getCard().show(main.getPp(), "orderc");
                main.setImg(priNum);
                detailVisible(false, priNum);
                main.getfoodCustInfo(custid, priNum);
            }
        });
    }

    // 음식 상세정보 출력
    public void detailVisible(boolean flag, int priNum) {
        this.priNum = priNum;
        setImg(priNum);
        jf.setVisible(flag);
        // yogio Model객체 사용을 위한 선언.
        YogioInter ref = new YogioModel();
        FoodInfoDTO vo = ref.selectFood(priNum);
        detailCatev.setText(vo.getFoodCategory()); // 음식카테고리
        detailFoodnmv.setText(vo.getFoodName()); // 음식명
        detailFoodprv.setText(String.valueOf(vo.getFoodPrice())); // 음식가격
        detailFoodInfo.setText(vo.getFoodDetail()); // 음식상세설명
    }

    public void setImg(int num) {
        num = priNum;
        foodImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("../foodimage/" + num + ".jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodImage = new javax.swing.JLabel();
        cateL = new javax.swing.JLabel();
        detailCatev = new javax.swing.JTextField();
        cateNmL = new javax.swing.JLabel();
        detailFoodnmv = new javax.swing.JTextField();
        catePrL = new javax.swing.JLabel();
        detailFoodprv = new javax.swing.JTextField();
        cateDetail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailFoodInfo = new javax.swing.JTextArea();
        detailOrderBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(650, 800));

        foodImage.setBackground(new java.awt.Color(255, 255, 255));

        cateL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cateL.setText("음식분류 : ");

        detailCatev.setEditable(false);

        cateNmL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cateNmL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cateNmL.setText("음식명 : ");

        detailFoodnmv.setEditable(false);

        catePrL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        catePrL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        catePrL.setText("가격 : ");

        detailFoodprv.setEditable(false);
        detailFoodprv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailFoodprvActionPerformed(evt);
            }
        });

        cateDetail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cateDetail.setText("음식상세설명");

        detailFoodInfo.setEditable(false);
        detailFoodInfo.setColumns(20);
        detailFoodInfo.setRows(5);
        jScrollPane1.setViewportView(detailFoodInfo);

        detailOrderBtn.setText("주문하기");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(cateDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(foodImage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(catePrL)
                                .addGap(23, 23, 23)
                                .addComponent(detailFoodprv, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cateNmL)
                                .addGap(18, 18, 18)
                                .addComponent(detailFoodnmv, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cateL, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(detailCatev, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(detailOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(foodImage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cateL)
                            .addComponent(detailCatev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detailFoodnmv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cateNmL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catePrL)
                            .addComponent(detailFoodprv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(cateDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(detailOrderBtn)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void detailFoodprvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailFoodprvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailFoodprvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cateDetail;
    private javax.swing.JLabel cateL;
    private javax.swing.JLabel cateNmL;
    private javax.swing.JLabel catePrL;
    private javax.swing.JTextField detailCatev;
    private javax.swing.JTextArea detailFoodInfo;
    private javax.swing.JTextField detailFoodnmv;
    private javax.swing.JTextField detailFoodprv;
    private javax.swing.JButton detailOrderBtn;
    private javax.swing.JLabel foodImage;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
